name: "📚 Learn"
description: Start a learning checklist
title: "[Learn] <name>"
labels: [Learning]
assignees:
  - kaiwalyakoparkar
body:
  - type: checkboxes
    attributes:
      label: Tracking list
      options:
        - label: Learn
          required: false
        - label: Create Practical Demo
          required: false
        - label: Write blog
          required: false
        - label: Create Video
          required: false
        - label: Add to notes repo
          required: false