apiVersion: apps/v1
kind: Deployment
metadata:
  name: wmd
spec:
  selector:
    matchLabels:
      app: wmd
  replicas: 2
  template:
    metadata:
      labels:
        app: wmd
    spec:
      containers:
      - name: wmd-ctr
        image: kaiwalyakoparkar/wemakedevs:1.0
        ports:
        - containerPort: 3000
